# configs/two_tower.yaml (MODIFIED)

training:
  # Data paths
  frozen_item_model_path: "gs://your-bucket/models/hh_item_two_tower/best_model.pt"  # NEW
  train_ratio: 0.8
  batch_size: 256
  negatives_per_pos: 5
  
  # Model architecture
  hidden_dim: 128  # For attribute alignment network
  output_dim: 64
  dropout: 0.2
  
  # Training
  epochs: 10
  lr: 0.001
  
  # Evaluation
  top_k: [10, 20, 50]